#!/bin/sh
commit_msg_file=$1
commit_source=$2
pattern="^(fix|feat|comment|docs|test|refactor|cicd|typing|style|module|structure|chore)[:][ ].+$"
if [ "$commit_source" = "message" ]; then
    commit_msg=$(cat "$commit_msg_file")
    if ! echo "$commit_msg" | grep -iqE "$pattern"; then
        echo "YOU DID NOT MATCH COMMIT CONVENTION!!!!"
        exit 1
    fi
fi