version: "3"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - /home/ubuntu/compose/db/data/mongodb:/data/db
    environment:
      - TZ=Asia/Seoul
    ports:
      - 6363:6379
    command: redis-server --requirepass 1q2w3e4r --port 6379
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Seoul
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
      - MONGO_INITDB_DATABASE=soborodb
  mariadb:
    container_name: mariadb
    image: mariadb:10.11.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/compose/db/data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=213748ry127howeq8hfoq348fhawer8tjwrefgohiaewogihq34y7wert5
      - MARIADB_DATABASE=soborodb
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=test1234
      - TZ=Asia/Seoul
networks:
  default:
    external:
      name: back-net
